### ISSUE TITLE
Problem with installation and running the programm

### ISSUE THREAD

**Issue by surajmetha55** [dariocazzani/COVID-19-trends#1]
I tried following command using python 3.5.2

`pip install -r requirements.txt`

It is giving me below error:
```
ERROR: Could not find a version that satisfies the requirement matplotlib==3.2.1 (from -r requirements.txt (line 6)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 3.0.0rc2, 3.0.0, 3.0.1, 3.0.2, 3.0.3)
ERROR: No matching distribution found for matplotlib==3.2.1 (from -r requirements.txt (line 6))
```
After installing different version of  matplotlib and running following command:

`python run_countries.py Japan`

It is giving me following error:

```
Traceback (most recent call last):
  File "run_countries.py", line 6, in <module>
    from utils.plot import plot_cases, plot_growth
  File "C:\Users\Suraj\Desktop\COVID-19-trends-master\COVID-19-trends-master\utils\plot.py", line 16
    plt.xlabel(f"Days since February 22 2020")

```

**Comment by dariocazzani** [comment]
I am afraid I wrongly put Python 3.5 or greater as a requirement.
It should be Python 3.6 or greater.

Sorry for the inconvenience.

**Comment by surajmetha55** [comment]
Thank you for your reply. Issue has been resolved.
